CREATE TABLE `resources` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(500) NOT NULL,
	`creator` varchar(300),
	`year` int,
	`type` varchar(50) NOT NULL DEFAULT 'other',
	`url` text,
	`description` text,
	`imageUrl` text,
	`themes` text,
	`tags` text,
	`language` varchar(10),
	`location` varchar(300),
	`latitude` varchar(20),
	`longitude` varchar(20),
	`quoteText` text,
	`videoUrl` text,
	`aspectRatio` varchar(10),
	`dominantHue` float,
	`addedBy` int,
	`addedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `resources_id` PRIMARY KEY(`id`)
);
